<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEgEJPa6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEgEJPa6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEgEJPa6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEgEJPa6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEgEJPa6\App_KernelDevDebugContainer([
    'container.build_hash' => 'EgEJPa6',
    'container.build_id' => '87f0a41e',
    'container.build_time' => 1575221449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEgEJPa6');
