<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfKD6WH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfKD6WH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJfKD6WH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJfKD6WH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJfKD6WH\App_KernelDevDebugContainer([
    'container.build_hash' => 'JfKD6WH',
    'container.build_id' => '86942305',
    'container.build_time' => 1575277295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJfKD6WH');
